Updates to the happy path readme(s)
tektoncd/triggers pull request #730
Opened 2020-08-27 16:28 UTC by jjasghar

* Adam and I spent the 4th cd.foudation twitch stream making edits to
the readme(s) for a happy path deployment.

- Moved the getting-started to a more prominent location
- Added a note about how to get the ingress
subdomain/external IP for the webhook
- Made a note of secret name from above step, and
export the secreat to a yaml then edit namespace line to namespace and
import secreat back
- Added the value of "ExternalDomain" as a "minimal update"

Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Co-authored-by: Adam Roberts <aroberts@uk.ibm.com>

2020-08-27 16:34 UTC, a-roberts requested changes
Added my comments - mainly just nits and what could be a slight enhancement for the secret copying

Thanks for working on this @jjasghar! All for happy paths 😄

2020-08-27 16:34 UTC, a-roberts commented on docs/getting-started/README.md
> +You should take not of the _ingress_ subdomain, or the external IP of
nit: note

2020-08-27 16:34 UTC, a-roberts commented on docs/getting-started/README.md
> +- If you have a cluster secret for a Let's Encrypt cert already provisisoned
nit: provisioned

2020-08-27 16:34 UTC, a-roberts commented on docs/getting-started/README.md
> +  - ```bash
Looks like

```
kubectl get secret <name> --namespace=<namespace> --export -o yaml |\
   kubectl apply --namespace=<new namespace> -f -
```

would work too, taken from https://www.revsys.com/tidbits/copying-kubernetes-secrets-between-namespaces/

2020-08-27 16:34 UTC, a-roberts commented on docs/getting-started/README.md
> +- ExternalDomain: Update this to the to something other then `demo.iancoffey.com`
nit: update this to be*

2020-08-27 19:48 UTC, dibyom commented
Thanks @jjasghar @a-roberts 

Once the nits are addressed, this is good to go!

2020-08-28 03:38 UTC, savitaashture reviewed
/lgtm

2020-08-28 03:42 UTC, savitaashture commented
Can you squash the commits into one?

2020-09-01 16:30 UTC, dibyom commented
/approve
/lgtm

2020-09-01 16:33 UTC, merged