Add basic syntactical parsing of CEL filters and expressions.
tektoncd/triggers pull request #745
Opened 2020-09-07 15:47 UTC by bigkevmcd

# Changes

This does basic syntax checking of CEL interceptor Filters and Overlays.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Perform simple syntax checking of CEL filter and overlays in the Webhook validator.

This performs perfunctory syntax validation of the expressions in the interceptor, it won't detect logical errors (expressions that rely on JSON bodies).
```

2020-09-07 16:39 UTC, savitaashture requested changes
PR looks good to me 
Thank you :+1: 

Few minor comments

2020-09-07 16:39 UTC, savitaashture commented on pkg/apis/triggers/v1alpha1/event_listener_validation.go
> +				return apis.ErrInvalidValue(fmt.Errorf("failed to parse the CEL filter: %s", issues.Err()), "cel.filter")
```suggestion
				return apis.ErrInvalidValue(fmt.Errorf("failed to parse the CEL overlays: %s", issues.Err()), "cel.overlays")
```

2020-09-07 16:39 UTC, savitaashture commented on pkg/apis/triggers/v1alpha1/event_listener_validation_test.go
>  	}, {
Can we add a test case for invalid `overlays` also

2020-09-07 16:39 UTC, savitaashture commented on pkg/apis/triggers/v1alpha1/event_listener_validation.go
> +			if issues != nil && issues.Err() != nil {
```suggestion
			if_, issues := env.Parse(i.CEL.Filter); issues != nil && issues.Err() != nil {
```

2020-09-07 16:39 UTC, savitaashture commented on pkg/apis/triggers/v1alpha1/event_listener_validation.go
> +			if issues != nil && issues.Err() != nil {
```suggestion
			if _, issues := env.Parse(v.Expression); issues != nil && issues.Err() != nil {
```

2020-09-08 00:12 UTC, sravankumar777 commented
Added the reported github issue :)

https://github.com/tektoncd/triggers/issues/746

2020-09-08 06:28 UTC, savitaashture reviewed
/lgtm

2020-09-08 06:31 UTC, khrm reviewed
/lgtm

2020-09-08 06:44 UTC, khrm commented
/approve

2020-09-08 06:46 UTC, merged